<?php


function mymodule_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Modification for the form with the given form ID goes here. For example, if
  // FORM_ID is "user_register_form" this code would run only on the user
  // registration form.

$options_first = _ajax_example_get_first_dropdown_options();

$form['statename'] = array(
        '#type'=>'select',
        '#options'=>$options_first,
        '#required'=>TRUE,
        '#description'=>t('State'),
   			'#prefix' => '<div id="state" class="form-select">',
        '#suffix' => '</div>',
				'#default_value' => '',
        '#validated' => 'true',
				'#ajax' => array(
      		'event' => 'change',
      		'callback' => 'district_dropdown',
      		'wrapper' => 'district',
					'method' => 'replace',
    		),
);

$selected ='';
if(!empty($form_state->getValues('statename'))) {
  $selected = $form_state->getValue('statename','default');
}
else{
	$selected= key($options_first);
}


$options_second = _ajax_example_get_second_dropdown_options($selected);

$form['districtname'] = array(
    '#type' => 'select',
    '#prefix' => '<div id="district" class="form-select">',
    '#suffix' => '</div>',
    '#required'=>TRUE,
    '#description'=>t('District'),
    '#options' => $options_second,
    '#default_value' => '',
    '#validated' => 'true',
    '#ajax' => array(
      'event' => 'change',
      'callback' => 'city_dropdown',
      'wrapper' => 'city',
      'method' => 'replace',
    ),
  );


  $selected ='';
  if(!empty($form_state->getValues('districtname'))) {
  	$selected = $form_state->getValue('districtname','default');
  }
  else{
  	$selected= key($options_second);
  }

$options_third = _ajax_example_get_third_dropdown_options($selected);
$form['cityname'] = array(
      '#type' => 'select',
      '#prefix' => '<div id="city" class="form-select">',
      '#suffix' => '</div>',
      '#required'=>TRUE,
      '#description'=>t('City'),
      '#options' => $options_third,
      '#default_value' => '',
      '#validated' => 'true',
    );
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'mymodule_user_form_submit';
      }
    }
}

function district_dropdown($form, $form_state) {
  return $form['districtname'];
}

function city_dropdown($form, $form_state) {
  return $form['cityname'];
}


function _ajax_example_get_first_dropdown_options() {

$sql = "SELECT DISTINCT State_Name FROM state_district_city ORDER BY State_Name ASC";
$results = db_query($connection, $sql);
$options = array();
$options[0]='Select';
while ($row = $results->fetchAssoc()) {
$options[$row['State_Name']] = $row['State_Name'];
//echo $row['State_code'];
  }
    return $options;
}


function _ajax_example_get_second_dropdown_options($key) {

$sql = "SELECT DISTINCT District_Name FROM state_district_city where State_Name='$key'";
$results = db_query($connection, $sql);
$options = array();
$options[0]='Select';
while ($row = $results->fetchAssoc()) {
$options[$row['District_Name']] = $row['District_Name'];
  }


return $options;


}

function _ajax_example_get_third_dropdown_options($key) {

$sql = "SELECT DISTINCT City_Name FROM state_district_city where District_Name='$key'";
$results = db_query($connection, $sql);
$options = array();
$options[0]='Select';
while ($row = $results->fetchAssoc()) {
$options[$row['City_Name']] = $row['City_Name'];
  }
return $options;
}

function mymodule_user_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $entity = $form_state->getFormObject()->getEntity();
 // mymodule_do_something($node);

$s = $form_state->getValue('statename');
$d = $form_state->getValue('districtname');
$c = $form_state->getValue('cityname');
 $entity->set('field_city', $c);
 $entity->set('field_state', $s);
 $entity->set('field_district', $d);
 $entity->save();
 \Drupal::logger(' mymodule')->notice('mymodule submit ') ;
 
}
?>
